
services:
  - type: web
    name: face-access-control
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    branch: main
